version: "3.8"

networks:
  interna_mreza:
    driver: bridge

services:
  authapi:
    build: ./authAPI
    ports:
      - "9000:9000"
    networks:
      - interna_mreza

  socialapi:
    build: ./socialAPI
    ports:
      - "3500:3500"
    networks:
      - interna_mreza
    depends_on:
      - authapi
